kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-role-binding
  annotations:
    argocd.argoproj.io/sync-wave: "0"
subjects:
  - kind: ServiceAccount
    name: openshift-gitops-argocd-application-controller
    namespace: openshift-gitops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: patching-cluster-role
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: patching-cluster-role
  annotations:
    argocd.argoproj.io/sync-wave: "0"
rules:
- apiGroups: ["authorization.openshift.io/v1", "rbac.authorization.k8s.io/v1"]
  resources: ["clusterrolebindings"]
  verbs: ["patch"]
  resourceNames: ["self-provisioners"]