apiVersion: authorization.openshift.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "false"
    argocd.argoproj.io/sync-wave: "1"
  name: self-provisioners