apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: logging-application
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/sveno1990/sno-azure
    targetRevision: HEAD
    path: configuration/cluster/openshift-logging
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-config
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
  ignoreDifferences:
  - group: operators.coreos.com
    kind: Subscription
    jsonPointers:
    - /spec/startingCSV