apiVersion: v1
kind: Namespace
metadata:
  name: openshift-operators-redhat 
  annotations:
    openshift.io/node-selector: ""
  labels:
    openshift.io/cluster-monitoring: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-logging 
annotations:
  openshift.io/node-selector: ""
  argocd.argoproj.io/sync-wave: "1"
labels:
    openshift.io/cluster-logging: "true"
    openshift.io/cluster-monitoring: "true" 